import BreadCrumb from "@/components/TourListing/bread-crumb";
import ClientProvider from "@/components/Common/client-provider";
import Filter from "@/components/Common/filter";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section>
      <div className="container">
        <BreadCrumb />
        <Filter onChange={true} enableTabs={true} />
        <div className="mt-4 mb-16">{children}</div>
      </div>
    </section>
  );
}
